- name: Run proxy container
  docker_container:
    name: httpd
    image: yosrabbassi/tp-devops-httpd
    ports:
      - "80:80"
    networks:
      - name: my-network

    state: started---
# tasks file for roles/launch_proxy
