- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-venv
    state: latest
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: Install Python3 and pip3
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Create a virtual environment for Docker SDK
  command: python3 -m venv /opt/docker_venv
  args:
    creates: /opt/docker_venv  # Only runs if this directory doesn’t exist

- name: Install Docker SDK for Python in virtual environment
  pip:
    requirements: /opt/docker_venv/requirements.txt  # Use a requirements file for clarity
    virtualenv: /opt/docker_venv
  when: docker_sdk_installed is not defined or not docker_sdk_installed

- name: Make sure Docker is running
  service:
    name: docker
    state: started
  tags: docker
---
# tasks file for roles/docker
